# Generated by Django 5.2.7 on 2025-10-21 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('hospital', 'Hospital'), ('patient', 'Patient')], max_length=10),
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='donor_profiles/')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('chronic_disease', models.TextField(blank=True, null=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('agree_donate', models.BooleanField(default=False)),
                ('terms', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=150)),
                ('hospital_id', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='hospital_profiles/')),
                ('blood_units_A_plus', models.PositiveIntegerField(default=0)),
                ('blood_units_A_minus', models.PositiveIntegerField(default=0)),
                ('blood_units_B_plus', models.PositiveIntegerField(default=0)),
                ('blood_units_B_minus', models.PositiveIntegerField(default=0)),
                ('blood_units_O_plus', models.PositiveIntegerField(default=0)),
                ('blood_units_O_minus', models.PositiveIntegerField(default=0)),
                ('blood_units_AB_plus', models.PositiveIntegerField(default=0)),
                ('blood_units_AB_minus', models.PositiveIntegerField(default=0)),
                ('storage_capacity', models.PositiveIntegerField(default=0)),
                ('requests', models.TextField(blank=True, null=True)),
                ('services_provided', models.TextField(blank=True, null=True)),
                ('license_upload', models.FileField(blank=True, null=True, upload_to='hospital_licenses/')),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group_needed', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='patient_profiles/')),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_condition', models.TextField(blank=True, null=True)),
                ('units_required', models.PositiveIntegerField()),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True)),
                ('date_required', models.DateField(blank=True, null=True)),
                ('physician_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('prescription', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
