# Generated by Django 5.2.7 on 2025-10-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0002_alter_profile_role_donorprofile_hospitalprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalprofile',
            old_name='profile_pic',
            new_name='Hospital_Logo',
        ),
        migrations.RenameField(
            model_name='hospitalprofile',
            old_name='contact_number',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='agree_donate',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='blood_units_AB_minus',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='blood_units_AB_plus',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='blood_units_A_minus',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='blood_units_A_plus',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='blood_units_B_minus',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='blood_units_B_plus',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='blood_units_O_minus',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='blood_units_O_plus',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='physician_contact',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='profile_pic',
        ),
    ]
