# Generated by Django 5.2.7 on 2025-10-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0003_rename_profile_pic_hospitalprofile_hospital_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='services_provided',
        ),
    ]
