# Generated by Django 5.2.7 on 2025-10-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='hemoglobin',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='last_donation_date',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='medicine_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
