# Generated by Django 5.2.7 on 2025-10-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0011_bloodrequest_is_emergency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='height',
        ),
    ]
