# Generated by Django 5.2.7 on 2025-10-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0012_remove_donorprofile_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='chronic_disease',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='medicine_details',
        ),
    ]
