# Generated by Django 5.2.7 on 2025-10-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0014_donorappointmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorappointmentrequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
