# Generated by Django 5.2.7 on 2025-11-02 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0015_donorappointmentrequest_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BB_app.hospitalprofile'),
        ),
    ]
