# Generated by Django 5.2.7 on 2025-11-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0016_alter_bloodstock_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodstock',
            name='units',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
