# Generated by Django 5.2.7 on 2025-11-03 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0017_bloodstock_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='hospital',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hospital', 'Hospital'), ('donor', 'Donor'), ('patient', 'Patient')], default='admin', max_length=20),
        ),
    ]
