# Generated by Django 5.2.7 on 2025-11-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0020_alter_notification_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='blood_group_needed',
            new_name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='date_required',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='units_required',
        ),
    ]
