# Generated by Django 5.2.7 on 2025-11-05 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0021_rename_blood_group_needed_patientprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='patient_name',
        ),
        migrations.CreateModel(
            name='PatientBloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_requested', models.PositiveIntegerField()),
                ('date_required', models.DateField()),
                ('is_emergency', models.BooleanField(default=False)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BB_app.patientprofile')),
            ],
        ),
    ]
