# Generated by Django 5.2.7 on 2025-11-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0022_remove_bloodrequest_patient_name_patientbloodrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientbloodrequest',
            old_name='date_required',
            new_name='date_Required',
        ),
        migrations.RenameField(
            model_name='patientbloodrequest',
            old_name='is_emergency',
            new_name='is_Emergency',
        ),
        migrations.RenameField(
            model_name='patientbloodrequest',
            old_name='units_requested',
            new_name='units_Requested',
        ),
        migrations.AddField(
            model_name='patientbloodrequest',
            name='hospital_Name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
