# Generated by Django 5.2.7 on 2025-11-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0023_rename_date_required_patientbloodrequest_date_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbloodrequest',
            name='hospital_Name',
            field=models.CharField(max_length=40),
        ),
    ]
