# Generated by Django 5.2.7 on 2025-11-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0024_alter_patientbloodrequest_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Expired', 'Expired')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientbloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Expired', 'Expired')], default='Pending', max_length=10),
        ),
    ]
