# Generated by Django 5.2.7 on 2025-11-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0025_alter_bloodrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorappointmentrequest',
            name='donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorappointmentrequest',
            name='donation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
