# Generated by Django 5.2.7 on 2025-11-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB_app', '0026_donorappointmentrequest_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorappointmentrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Date Sent', 'Date Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Donated', 'Donated')], default='Pending', max_length=20),
        ),
    ]
